name: flutter_imc_app
description: An application for calculating your BMI (IMC)
version: 1.0.0

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
